// <auto-generated />
using System;
using EcoleApp.Models.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcoleApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251226202808_SeedRolesAndAdmin")]
    partial class SeedRolesAndAdmin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("EcoleApp.Models.Entity.AdministrationEtAudit.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateAction")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.Property<string>("UtilisateurId1")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId1");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("EcoleApp.Models.Entity.AdministrationEtAudit.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("EcoleApp.Models.Entity.Auth.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NomRole")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Responsabilite")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NomRole = "Admin",
                            Responsabilite = "Gestion complète du système"
                        },
                        new
                        {
                            Id = 2,
                            NomRole = "Enseignant",
                            Responsabilite = "Gestion des séances et présences"
                        },
                        new
                        {
                            Id = 3,
                            NomRole = "Etudiant",
                            Responsabilite = "Consultation des présences"
                        },
                        new
                        {
                            Id = 4,
                            NomRole = "Delegue",
                            Responsabilite = "Gestion des présences de la classe"
                        });
                });

            modelBuilder.Entity("EcoleApp.Models.Entity.Auth.Utilisateur", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NomComplet")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Utilisateurs");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Utilisateur");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("EcoleApp.Models.Entity.JustificationDesHeures.Justificatif", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateDepot")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EtudiantId")
                        .HasColumnType("int");

                    b.Property<string>("EtudiantId1")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FichierUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("EtudiantId1");

                    b.ToTable("Justificatifs");
                });

            modelBuilder.Entity("EcoleApp.Models.Entity.Notification.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateEnvoi")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("EstLu")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.Property<string>("UtilisateurId1")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId1");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("EcoleApp.Models.Entity.RapportEtStatistique.RapportAssiduite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateGeneration")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FichierUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Rapports");
                });

            modelBuilder.Entity("EcoleApp.Models.Entity.SeanceDeCours.CahierDeTexte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Activites")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("CoursId")
                        .HasColumnType("int");

                    b.Property<string>("Devoirs")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EnseignantId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Objectif")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Ressources")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SeanceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CoursId");

                    b.HasIndex("EnseignantId");

                    b.HasIndex("SeanceId")
                        .IsUnique();

                    b.ToTable("CahiersDeTexte");
                });

            modelBuilder.Entity("EcoleApp.Models.Entity.SeanceDeCours.Cours", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Annee")
                        .HasColumnType("int");

                    b.Property<int>("EnseignantId")
                        .HasColumnType("int");

                    b.Property<string>("EnseignantId1")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Semestre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("VolumeHoraire")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EnseignantId1");

                    b.ToTable("Cours");
                });

            modelBuilder.Entity("EcoleApp.Models.Entity.SeanceDeCours.Groupe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Groupes");
                });

            modelBuilder.Entity("EcoleApp.Models.Entity.SeanceDeCours.Seance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CoursId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("GroupeId")
                        .HasColumnType("int");

                    b.Property<string>("Salle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("ValideDelegue")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ValideEnseignant")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("CoursId");

                    b.HasIndex("GroupeId");

                    b.ToTable("Seances");
                });

            modelBuilder.Entity("EcoleApp.Models.Entity.Auth.Admin", b =>
                {
                    b.HasBaseType("EcoleApp.Models.Entity.Auth.Utilisateur");

                    b.Property<string>("Poste")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasDiscriminator().HasValue("Admin");

                    b.HasData(
                        new
                        {
                            Id = "ADMIN-001",
                            Email = "admin@asp.com",
                            MotDePasse = "BWawV55i2M4l1tSYbOykgyHH4qslJWo8Bxxg/R9smkI=",
                            NomComplet = "Administrateur Principal",
                            RoleId = 1,
                            Poste = "Administrateur Système"
                        });
                });

            modelBuilder.Entity("EcoleApp.Models.Entity.Auth.Enseignant", b =>
                {
                    b.HasBaseType("EcoleApp.Models.Entity.Auth.Utilisateur");

                    b.Property<string>("Specialite")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasDiscriminator().HasValue("Enseignant");
                });

            modelBuilder.Entity("EcoleApp.Models.Entity.Auth.Etudiant", b =>
                {
                    b.HasBaseType("EcoleApp.Models.Entity.Auth.Utilisateur");

                    b.Property<string>("Filiere")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("GroupeId")
                        .HasColumnType("int");

                    b.Property<string>("Matricule")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Niveau")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasIndex("GroupeId");

                    b.HasDiscriminator().HasValue("Etudiant");
                });

            modelBuilder.Entity("EcoleApp.Models.Entity.AdministrationEtAudit.AuditLog", b =>
                {
                    b.HasOne("EcoleApp.Models.Entity.Auth.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId1");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("EcoleApp.Models.Entity.Auth.Utilisateur", b =>
                {
                    b.HasOne("EcoleApp.Models.Entity.Auth.Role", "Role")
                        .WithMany("Utilisateurs")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("EcoleApp.Models.Entity.JustificationDesHeures.Justificatif", b =>
                {
                    b.HasOne("EcoleApp.Models.Entity.Auth.Etudiant", "Etudiant")
                        .WithMany()
                        .HasForeignKey("EtudiantId1");

                    b.Navigation("Etudiant");
                });

            modelBuilder.Entity("EcoleApp.Models.Entity.Notification.Notification", b =>
                {
                    b.HasOne("EcoleApp.Models.Entity.Auth.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId1");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("EcoleApp.Models.Entity.SeanceDeCours.CahierDeTexte", b =>
                {
                    b.HasOne("EcoleApp.Models.Entity.SeanceDeCours.Cours", "Cours")
                        .WithMany()
                        .HasForeignKey("CoursId");

                    b.HasOne("EcoleApp.Models.Entity.Auth.Enseignant", "Enseignant")
                        .WithMany()
                        .HasForeignKey("EnseignantId");

                    b.HasOne("EcoleApp.Models.Entity.SeanceDeCours.Seance", null)
                        .WithOne("CahierDeTexte")
                        .HasForeignKey("EcoleApp.Models.Entity.SeanceDeCours.CahierDeTexte", "SeanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cours");

                    b.Navigation("Enseignant");
                });

            modelBuilder.Entity("EcoleApp.Models.Entity.SeanceDeCours.Cours", b =>
                {
                    b.HasOne("EcoleApp.Models.Entity.Auth.Enseignant", "Enseignant")
                        .WithMany()
                        .HasForeignKey("EnseignantId1");

                    b.Navigation("Enseignant");
                });

            modelBuilder.Entity("EcoleApp.Models.Entity.SeanceDeCours.Seance", b =>
                {
                    b.HasOne("EcoleApp.Models.Entity.SeanceDeCours.Cours", "Cours")
                        .WithMany()
                        .HasForeignKey("CoursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoleApp.Models.Entity.SeanceDeCours.Groupe", "Groupe")
                        .WithMany()
                        .HasForeignKey("GroupeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cours");

                    b.Navigation("Groupe");
                });

            modelBuilder.Entity("EcoleApp.Models.Entity.Auth.Etudiant", b =>
                {
                    b.HasOne("EcoleApp.Models.Entity.SeanceDeCours.Groupe", null)
                        .WithMany("Etudiants")
                        .HasForeignKey("GroupeId");
                });

            modelBuilder.Entity("EcoleApp.Models.Entity.Auth.Role", b =>
                {
                    b.Navigation("Utilisateurs");
                });

            modelBuilder.Entity("EcoleApp.Models.Entity.SeanceDeCours.Groupe", b =>
                {
                    b.Navigation("Etudiants");
                });

            modelBuilder.Entity("EcoleApp.Models.Entity.SeanceDeCours.Seance", b =>
                {
                    b.Navigation("CahierDeTexte");
                });
#pragma warning restore 612, 618
        }
    }
}
